### ISSUE TITLE
Science Corvette Type C Enhanced Cloaking System doesn't work

### ISSUE THREAD

**Issue by Staranen** [arcburnergit/RAD-FTL-MV-Addon#14]
The enemy Shields room is lit up for a second, then the hacking SFX comes on with the room turning purple, but with weapons on or off it does not hack them in any way.

![image](https://github.com/arcburnergit/RAD-FTL-MV-Addon/assets/125708349/70b82193-4825-40bd-97e0-7383c479a791)

**Comment by arcburnergit** [comment]
will be fixed in next release.
