### ISSUE TITLE
If Experiment 26 is a ghost/phantom then why the lab upgrades doesn't show ghosts option.

### ISSUE THREAD

**Issue by AdvintasAHAT86420** [arcburnergit/RAD-FTL-MV-Addon#2]
Here's an image showing that the Ghosts option in Lab Upgrades doesn't show while 26 is present.
![Ghost-26-Lab-Issue](https://github.com/arcburnergit/RAD-FTL-MV-Addon/assets/82627347/08c050d5-2024-458e-82a8-4a19df0d8308)
Since that option requires LIST_CREW_GHOST and contains all the ghost races, So the solution is to append 26 to that requires list in autoBlueprint.xml.append.
![Ghost-Lab](https://github.com/arcburnergit/RAD-FTL-MV-Addon/assets/82627347/9d167a14-963d-46da-96e4-854a07179ac2)
![Ghost-Lab-List](https://github.com/arcburnergit/RAD-FTL-MV-Addon/assets/82627347/91c76afa-5b86-43cf-806c-53328f20797d)

**Comment by arcburnergit** [comment]
Yeah, this just involves me going through and checking to make sure all the crew and weapons are in the right blueprint lists, It will definently be done before 1.0 releases.
