### ISSUE TITLE
Time wrecker crusier's Warped Hull Plating says it gives 5 temp hull, but only gives 1.

### ISSUE THREAD

**Issue by Duodecimus** [arcburnergit/RAD-FTL-MV-Addon#8]
Error is in hyperspace.xml.append, line 674

`  <aug name="RAD_TIME_HULL">`
`    <function name="RAD_SUPERHULL" value="1" useForReqs="false" warning="false" />`
`    <function name="AUTO_COOLDOWN" value="-0.25" useForReqs="false" warning="false" />`
`    <locked />`
`  </aug>`

Superhull value should be 5

**Comment by arcburnergit** [comment]
This was changed due to it being too strong otherwise, I'll update the description to reflect that.
