### ISSUE TITLE
Time Wrecker's augment sometimes doesn't activate

### ISSUE THREAD

**Issue by Duodecimus** [arcburnergit/RAD-FTL-MV-Addon#9]
I'm pretty sure it's because this loop
`       for weapon in vter(shipManager:GetWeaponList()) do`
`           if not weapon:IsChargedGoal() then `
`               log("Add weapon")`
`          table.insert(weaponList, weapon)`
`          weaponCount = weaponCount + 1`
`      end`
doesn't care if a weapon is powered or not
so it picks a uncharged weapon at random, and if that weapon is unpowered it does nothing

The if should probably be 
`           if (not weapon:IsChargedGoal()) and weapon.powered then `

**Comment by arcburnergit** [comment]
Implemented.
